replicaCount: 1
image:
  repository: docker-registry.market.local/evo-ui-kit
  tag:
service:
  name: evo-ui-kit
  internalPort: 80
  externalPort: 80
resources:
  requests:
    memory: 100Mi
  limits:
    memory: 200Mi
ingress:
  enabled: false
  host: test
    
