name: Release
on:
  release:
    types:
      - created
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
    - name: Send telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.FRONTEND_TELEGRAM_CHAT }}
        token: ${{ secrets.FRONTEND_TELEGRAM_BOT }}
        message: |
          test ${{github.event.tag}}
